name: Deploy Dev

env:
  AWS_REGION: eu-north-1
  AWS_IAM_ROLE: arn:aws:iam::703671934401:role/github-actions

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [dev]

permissions:
  id-token: write
  contents: write

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'dev' }}
    environment: dev
    runs-on: [ubuntu-22.04]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
